### ISSUE TITLE
Automatic reconnect causes duplicate responses

### ISSUE THREAD

**Issue by afex** [hipchat/hubot-hipchat#192]
Seemingly related to #174, anytime hubot loses connection with hipchat and reconnects all future bot responses are doubled. If the bot reconnects again before it is restarted, then all bot responses are tripled.  This continues until the process is restarted.

**Comment by facundofarias** [comment]
Should this be solved? We are still facing this issue sometimes.

**Comment by spruce** [comment]
Yes. It actually should be fixed through the pull request I referenced. Can you give a narrower description when that happens?

**Comment by keen99** [comment]
this definitely still happens to me - taking a quick look, I'm assuming that #206 would fix it, if it were in the npm package. :)

It's very simple to reproduce - just change your bot's "full name" via API or the edit profile interface in hipchat while the bot is connected:

```
[Fri Jan 30 2015 16:47:29 GMT+0000 (UTC)] INFO Disconnected from hipchat.com
[Fri Jan 30 2015 16:47:29 GMT+0000 (UTC)] INFO Waiting 7s and then retrying...
[Fri Jan 30 2015 16:47:29 GMT+0000 (UTC)] ERROR null, null, { name: 'stream:error',
  parent: null,
  attrs: { 'xmlns:stream': 'http://etherx.jabber.org/streams' },
  children:
   [ { name: 'service-unavailable',
       parent: [Circular],
       attrs: { xmlns: 'urn:ietf:params:xml:ns:xmpp-streams' },
       children: [] },
     { name: 'text',
       parent: [Circular],
       attrs: { xmlns: 'urn:ietf:params:xml:ns:xmpp-streams' },
       children: [ 'Your account information has been updated.' ] } ] }
[Fri Jan 30 2015 16:47:29 GMT+0000 (UTC)] INFO Connection was closed
[Fri Jan 30 2015 16:47:29 GMT+0000 (UTC)] INFO Disconnected from hipchat.com
[Fri Jan 30 2015 16:47:29 GMT+0000 (UTC)] INFO Connection went offline
[Fri Jan 30 2015 16:47:29 GMT+0000 (UTC)] INFO Disconnected from hipchat.com
[Fri Jan 30 2015 16:47:36 GMT+0000 (UTC)] INFO Attempting to reconnect...
[Fri Jan 30 2015 16:47:36 GMT+0000 (UTC)] INFO Connecting HipChat adapter...
[Fri Jan 30 2015 16:47:37 GMT+0000 (UTC)] INFO Connected to hipchat.com as @zcebot
[Fri Jan 30 2015 16:47:37 GMT+0000 (UTC)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web_url | cut -d= -f2)`
[Fri Jan 30 2015 16:47:37 GMT+0000 (UTC)] INFO Discovered redis from REDIS_URL environment variable
[Fri Jan 30 2015 16:47:37 GMT+0000 (UTC)] INFO Data for zcebot brain retrieved from Redis
LOG: @ZCE trigger hit - [ '@zce ', '@zce ', ' ', index: 0, input: '@zce test 23' ] -- bot name - zcebot - room name - zce_bot_test
LOG: @ZCE trigger hit - [ '@zce ', '@zce ', ' ', index: 0, input: '@zce test 23' ] -- bot name - zcebot - room name - zce_bot_test
```

**Comment by spruce** [comment]
Until it gets pushed to npm, you probably wanna use my git repo: https://github.com/spruce/hubot-hipchat as source in package.json. Like this:
```
"hubot-hipchat": "git://github.com/spruce/hubot-hipchat",
```

**Comment by thepuzzlemaster** [comment]
Is there a reason the latest version isn't getting pushed to NPM? It was merged back into master already.

**Comment by rbergman** [comment]
Latest PR merges have been pushed to npm.
